### ISSUE TITLE
Is it possible to connect to `LCP server`?

### ISSUE THREAD

**Issue by sgalcheung** [NYPL/web-reader#161]
I am newer for DRM, and I noticed this repo could [support DRM](https://github.com/NYPL-Simplified/web-reader?tab=readme-ov-file#decryption), also I read [Readium Architecture](https://readium.org/architecture/), and it seems two difference solutions, for desktop(or mobile), used LCP（Lightweight Content Protection）, for web, used Webpub Manifest, because backend server can commutation with other services, so, this is a large challenge to solve web DRM.

Has anyone met this problem? And how do you resolve it?

refer from [Web Origin Explainer: Practical Issues and Possible Solutions](https://readium.org/architecture/server/origin.html)

**Comment by killerpuppytails** [comment]
Hello! Per the FAQ maintained by the builder and maintainer of LCP, EDRLabs, LCP is not intended to be used for web applications. You can review their statement here: https://www.edrlab.org/readium-lcp/faq/

However, the Readium team and EDRLabs is discussing how to implement content protection on web. If that is a conversation you would like to join, feel free to posit this same question on Readium's web project repo here: https://github.com/readium/web

**Comment by sgalcheung** [comment]
by the way. have an example for [support DRM, by passing a getContent function to either the <WebReader> component or the useWebReader hook](https://github.com/NYPL-Simplified/web-reader?tab=readme-ov-file#decryption)?

**Comment by hokei** [comment]
Thank you for your question.  Many DRM systems work differently, and unfortunately we cannot provide an example, nor details regarding the solutions we use beyond the broad strokes outlined in the readme.

**Comment by sgalcheung** [comment]
I’m considering use radium DRM solution, and thank you replay.

获取 Outlook<https://aka.ms/qtex0l> for iOS
章思高
________________________________
